/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guipart1;

import java.awt.Component;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
//import java.nio.file.Files;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author willmbp15
 */
public class guilua extends javax.swing.JFrame {

  File infilefromlua;
  File outfileafterobfuscation;
  private Component frame;

  /**
   * Creates new form guilua
   */
  public guilua() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jFileChooser1 = new javax.swing.JFileChooser();
    jButton4 = new javax.swing.JButton();
    jFileChooser2 = new javax.swing.JFileChooser();
    jLabel8 = new javax.swing.JLabel();
    jCheckBox2 = new javax.swing.JCheckBox();
    jCheckBox3 = new javax.swing.JCheckBox();
    jCheckBox4 = new javax.swing.JCheckBox();
    jPanelLower = new javax.swing.JPanel();
    jLabelLuaIcon = new javax.swing.JLabel();
    jLabelObfuscationOptions = new javax.swing.JLabel();
    jLabelGetFileToObfuscate = new javax.swing.JLabel();
    jButtonGetLuaFile = new javax.swing.JButton();
    jLabelBottomIconImage = new javax.swing.JLabel();
    jLabelDeveloperCredits = new javax.swing.JLabel();
    jButtonObfuscate = new javax.swing.JButton();
    jButtonExitProgram = new javax.swing.JButton();
    jTextFieldMakeOutputFile = new javax.swing.JTextField();
    jLabelGetBlackListFile = new javax.swing.JLabel();
    jButtonGetBlackListFile = new javax.swing.JButton();
    jButtonMakeOutputFile = new javax.swing.JButton();
    jButtonGetLuaFolder = new javax.swing.JButton();
    jLabelLuaGuardObfuscatorv10 = new javax.swing.JLabel();

    jFileChooser1.setFileFilter(new LuaCustomFilter());
    jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jFileChooser1ActionPerformed(evt);
      }
    });

    jButton4.setText("jButton4");

    jFileChooser2.setFileFilter(new TextCustomFilter());

    jLabel8.setText("Types of Obfuscation");

    jCheckBox2.setText("Name Mangler");
    jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jCheckBox2ActionPerformed(evt);
      }
    });

    jCheckBox3.setText("Level 2");
    jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jCheckBox3ActionPerformed(evt);
      }
    });

    jCheckBox4.setText("Level 3");
    jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jCheckBox4ActionPerformed(evt);
      }
    });

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanelLower.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 4));

    jLabelLuaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guipart1/lua.gif"))); // NOI18N

    jLabelObfuscationOptions.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
    jLabelObfuscationOptions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabelObfuscationOptions.setText("         Obfuscation Options");

    jLabelGetFileToObfuscate.setText("Get File to Obfuscate");

    jButtonGetLuaFile.setText("Get Lua File");
    jButtonGetLuaFile.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonGetLuaFileActionPerformed(evt);
      }
    });

    jLabelBottomIconImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabelBottomIconImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guipart1/DSD-pku-uo.jpg"))); // NOI18N

    jLabelDeveloperCredits.setText("    LuaGuard is a joint project between PKU and UO Software developers");

    jButtonObfuscate.setText("Obfuscate");
    jButtonObfuscate.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonObfuscateActionPerformed(evt);
      }
    });

    jButtonExitProgram.setText("Exit Program");
    jButtonExitProgram.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonExitProgramActionPerformed(evt);
      }
    });

    jTextFieldMakeOutputFile.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    jTextFieldMakeOutputFile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    jTextFieldMakeOutputFile.setEnabled(false);
    jTextFieldMakeOutputFile.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldMakeOutputFileActionPerformed(evt);
      }
    });

    jLabelGetBlackListFile.setText("   Get Black List File");

    jButtonGetBlackListFile.setText("Get Black List File");
    jButtonGetBlackListFile.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonGetBlackListFileActionPerformed(evt);
      }
    });

    jButtonMakeOutputFile.setText("Make Output File");
    jButtonMakeOutputFile.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonMakeOutputFileActionPerformed(evt);
      }
    });

    jButtonGetLuaFolder.setText("Get Lua Folder");
    jButtonGetLuaFolder.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonGetLuaFolderActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanelLowerLayout = new javax.swing.GroupLayout(jPanelLower);
    jPanelLower.setLayout(jPanelLowerLayout);
    jPanelLowerLayout.setHorizontalGroup(
      jPanelLowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelLowerLayout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(jLabelLuaIcon)
        .addGap(24, 24, 24)
        .addGroup(jPanelLowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLowerLayout.createSequentialGroup()
            .addGroup(jPanelLowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jButtonMakeOutputFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jButtonObfuscate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanelLowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jButtonExitProgram, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
              .addComponent(jTextFieldMakeOutputFile)))
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLowerLayout.createSequentialGroup()
            .addGroup(jPanelLowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabelObfuscationOptions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLowerLayout.createSequentialGroup()
                .addComponent(jLabelGetFileToObfuscate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelGetBlackListFile))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLowerLayout.createSequentialGroup()
                .addComponent(jButtonGetLuaFile, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGetLuaFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGetBlackListFile, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(0, 168, Short.MAX_VALUE)))
        .addGap(76, 76, 76))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLowerLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabelDeveloperCredits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
      .addGroup(jPanelLowerLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabelBottomIconImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanelLowerLayout.setVerticalGroup(
      jPanelLowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelLowerLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelLowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabelLuaIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
          .addGroup(jPanelLowerLayout.createSequentialGroup()
            .addComponent(jLabelObfuscationOptions)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanelLowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabelGetFileToObfuscate)
              .addComponent(jLabelGetBlackListFile))
            .addGap(9, 9, 9)
            .addGroup(jPanelLowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jButtonGetLuaFile)
              .addComponent(jButtonGetBlackListFile)
              .addComponent(jButtonGetLuaFolder))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelLowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jTextFieldMakeOutputFile, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jButtonMakeOutputFile))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanelLowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jButtonObfuscate)
              .addComponent(jButtonExitProgram))
            .addGap(25, 25, 25)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabelDeveloperCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabelBottomIconImage, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    jLabelLuaGuardObfuscatorv10.setFont(new java.awt.Font("Malayalam MN", 0, 36)); // NOI18N
    jLabelLuaGuardObfuscatorv10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabelLuaGuardObfuscatorv10.setText("LuaGuard Obfuscator v1.0");
    jLabelLuaGuardObfuscatorv10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204), 4));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanelLower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(jLabelLuaGuardObfuscatorv10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jLabelLuaGuardObfuscatorv10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanelLower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed

    if (jCheckBox2.isSelected()) {
      System.out.println("Name Mangler CheckBox Selected");
    } else {
      System.out.println("Name Mangler CheckBox Unchecked");
    }


  }//GEN-LAST:event_jCheckBox2ActionPerformed

  private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
    if (jCheckBox3.isSelected()) {
      System.out.println("Level 2 Obfuscation CheckBox Selected");
    } else {
      System.out.println("Level 2 Obfuscation CheckBox Unchecked");
    }

  }//GEN-LAST:event_jCheckBox3ActionPerformed

  private void jButtonExitProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitProgramActionPerformed
    System.out.println("Exit Button Pressed");
    System.exit(0);
  }//GEN-LAST:event_jButtonExitProgramActionPerformed

  private void jButtonGetLuaFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetLuaFileActionPerformed
    System.out.println("Get file pressed");

    int returnVal = jFileChooser1.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
      this.infilefromlua = jFileChooser1.getSelectedFile();
      System.out.println(("The filename is " + infilefromlua.getName()));

      System.out.println("The File Selected is " + infilefromlua);
       // Do obfuscation with file

    } else {
      System.out.println("File access cancelled by user.");

//      File root = new File(path);
//      File[] list = root.listFiles();
//
//      if (list == null) {
//        return;
//      }
//
//      for (File f : list) {
//        if (f.isDirectory()) {
//          walk(f.getAbsolutePath());
//          System.out.println("Dir:" + f.getAbsoluteFile());
//        } else {
//          System.out.println("File:" + f.getAbsoluteFile());
//        }
//      }
    }


  }//GEN-LAST:event_jButtonGetLuaFileActionPerformed

  private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed

    if (jCheckBox4.isSelected()) {
      System.out.println("Level 3 Obfuscation CheckBox Selected");
    } else {
      System.out.println("Level 3 Obfuscation CheckBox Unchecked");
    }

  }//GEN-LAST:event_jCheckBox4ActionPerformed


  private void jButtonObfuscateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObfuscateActionPerformed
    System.out.println("Obfuscate Button Pressed");

  }//GEN-LAST:event_jButtonObfuscateActionPerformed

  private void jTextFieldMakeOutputFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMakeOutputFileActionPerformed
    //String outfilenamefromuserinput = jTextField1.getText();
    //File outfilename = new File(outfilenamefromuserinput);
    // for robustness need to not take input
    //System.out.println("Output FileName = " + outfilenamefromuserinput);

    //jTextField1.setText("Obfuscated_"+infilefromlua);
  }//GEN-LAST:event_jTextFieldMakeOutputFileActionPerformed

  private void jButtonGetBlackListFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetBlackListFileActionPerformed

    System.out.println("Get Black List File pressed");

    int returnVal = jFileChooser2.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
      File infile = jFileChooser2.getSelectedFile();

      System.out.println(("The filename is " + infile.getName()));
      System.out.println("The Black List File Selected is " + infile);

      try {
        String contents = "The BLACKLIST IS COMPRISED OF: " + new Scanner(infile).useDelimiter("\\Z").next();
        System.out.println("blacklist: " + contents);
        JOptionPane.showMessageDialog(frame, contents);

      } catch (FileNotFoundException ex) {
        Logger.getLogger(guilua.class.getName()).log(Level.SEVERE, null, ex);
      }

    } else {
      System.out.println("File access cancelled by user.");
    }


  }//GEN-LAST:event_jButtonGetBlackListFileActionPerformed

  private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
    String outfilenamefromuserinput = jTextFieldMakeOutputFile.getText();
    System.out.println("Output FileName = " + outfilenamefromuserinput);
    //jTextField1.setText("Obfuscated_"+infilefromlua.getName());
  }//GEN-LAST:event_jFileChooser1ActionPerformed

  private void jButtonMakeOutputFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMakeOutputFileActionPerformed
    //String outfilenamefromuserinput = jTextField1.getText();
    //System.out.println("Output FileName = " + outfilenamefromuserinput);

    if (infilefromlua == null) {
      JOptionPane.showMessageDialog(null,
              "Error! Please press the \"Get Lua File\" button first",
              "Error!",
              JOptionPane.ERROR_MESSAGE);
      return;
    }

    String stringforoutputfilename = "Obfuscated_" + infilefromlua.getName();
    jTextFieldMakeOutputFile.setText(stringforoutputfilename);
  }//GEN-LAST:event_jButtonMakeOutputFileActionPerformed

  private void jButtonGetLuaFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGetLuaFolderActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButtonGetLuaFolderActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(guilua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(guilua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(guilua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(guilua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new guilua().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButtonExitProgram;
  private javax.swing.JButton jButtonGetBlackListFile;
  private javax.swing.JButton jButtonGetLuaFile;
  private javax.swing.JButton jButtonGetLuaFolder;
  private javax.swing.JButton jButtonMakeOutputFile;
  private javax.swing.JButton jButtonObfuscate;
  private javax.swing.JCheckBox jCheckBox2;
  private javax.swing.JCheckBox jCheckBox3;
  private javax.swing.JCheckBox jCheckBox4;
  private javax.swing.JFileChooser jFileChooser1;
  private javax.swing.JFileChooser jFileChooser2;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabelBottomIconImage;
  private javax.swing.JLabel jLabelDeveloperCredits;
  private javax.swing.JLabel jLabelGetBlackListFile;
  private javax.swing.JLabel jLabelGetFileToObfuscate;
  private javax.swing.JLabel jLabelLuaGuardObfuscatorv10;
  private javax.swing.JLabel jLabelLuaIcon;
  private javax.swing.JLabel jLabelObfuscationOptions;
  private javax.swing.JPanel jPanelLower;
  private javax.swing.JTextField jTextFieldMakeOutputFile;
  // End of variables declaration//GEN-END:variables
}
